### PR TITLE
upgrade to react-native 0.40

### PR DESCRIPTION
**Pull request by bgdavidx**
adds support for react-native 0.40 (latest)

### CODE REVIEW

**Comment by cesardeazevedo** [comment]
Thank you so much.

**Comment by cesardeazevedo** [comment]
Should be `packson.json` dependencies as `peerDependencies`?

**Comment by bgdavidx** [comment]
they can be -- I was using npm 3 so it wasn't installing those dependencies. in npm 3 it only checks that "peerDependencies" are installed and prints a warning if not. I did want to force them to use a react-native version that would work with this package after the update though (0.40)

**Comment by bgdavidx** [comment]
let me know though - can make another PR if you prefer peerDependencies

**Comment by cesardeazevedo** [comment]
yeah, It's kind annoying, i don't think it should be as a regular dependency, i also saw some react-native libs removing `peerDependencies` off, i think i will do the same and ship as `0.1.0`

Thank you again.

**Pull request merged**
